[project]
name = "everything-in-markdown"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.9"
dependencies = [
    "markitdown>=0.1.4",
    "streamlit>=1.52.1",
]
